# Generated by Django 4.2.3 on 2023-07-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='comments',
            index_together=set(),
        ),
    ]
